//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.ModelsResource", typeof(ModelsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type is required.
        /// </summary>
        internal static string Account_AccountType {
            get {
                return ResourceManager.GetString("Account_AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created is required.
        /// </summary>
        internal static string Account_DateCreated {
            get {
                return ResourceManager.GetString("Account_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        internal static string Owner_Address_Required {
            get {
                return ResourceManager.GetString("Owner_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be longer than 100 characters.
        /// </summary>
        internal static string Owner_Address_StringLength {
            get {
                return ResourceManager.GetString("Owner_Address_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required.
        /// </summary>
        internal static string Owner_DateOfBirth {
            get {
                return ResourceManager.GetString("Owner_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string Owner_Name_Required {
            get {
                return ResourceManager.GetString("Owner_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be longer than 60 characters.
        /// </summary>
        internal static string Owner_Name_StringLength {
            get {
                return ResourceManager.GetString("Owner_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        internal static string OwnerForCreationDto_Address_Required {
            get {
                return ResourceManager.GetString("OwnerForCreationDto_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be loner then 100 characters.
        /// </summary>
        internal static string OwnerForCreationDto_Address_StringLength {
            get {
                return ResourceManager.GetString("OwnerForCreationDto_Address_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required.
        /// </summary>
        internal static string OwnerForCreationDto_DateOfBirth {
            get {
                return ResourceManager.GetString("OwnerForCreationDto_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string OwnerForCreationDto_Name_Required {
            get {
                return ResourceManager.GetString("OwnerForCreationDto_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be longer than 60 characters.
        /// </summary>
        internal static string OwnerForCreationDto_Name_StringLength {
            get {
                return ResourceManager.GetString("OwnerForCreationDto_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        internal static string OwnerForUpdateDto_Address_Required {
            get {
                return ResourceManager.GetString("OwnerForUpdateDto_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be loner then 100 characters.
        /// </summary>
        internal static string OwnerForUpdateDto_Address_StringLength {
            get {
                return ResourceManager.GetString("OwnerForUpdateDto_Address_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required.
        /// </summary>
        internal static string OwnerForUpdateDto_DateOfBirth {
            get {
                return ResourceManager.GetString("OwnerForUpdateDto_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string OwnerForUpdateDto_Name_Required {
            get {
                return ResourceManager.GetString("OwnerForUpdateDto_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be longer than 60 characters.
        /// </summary>
        internal static string OwnerForUpdateDto_Name_StringLength {
            get {
                return ResourceManager.GetString("OwnerForUpdateDto_Name_StringLength", resourceCulture);
            }
        }
    }
}
